workflows:
  android-build:
    name: Spinning Mill Breakage Android
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - rieterselva123@gmail.com
